spring:
  data:
    mongodb:
      username: stephen
      password: stephen
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090